@startuml
left to right direction
actor "Usuari de Biblioteca" as user
actor "Bibliotecari" as librarian

rectangle "Sistema de Gestió" {
  usecase "Demanar llibre" as UC1
  usecase "Prestar llibre" as UC2

}

user --> UC1
librarian --> UC2
@enduml